using AlSadatSeram.Services.contract;
using Domain.Enums;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Application.DTOs.FinanceDtos
{
    public class TreeAccountDto
    {
        public int? id { get; set; }
        public string accountName { get; set; } = default!;
        public string? accountCode { get; set; }
        public int? parentId { get; set; }
        public decimal? debit { get; set; }
        public bool isLeaf { get; set; }
        public bool isActive { get; set; }
        public decimal? credit { get; set; }
        public bool isSystemAccount { get; set; }   // NEW
        public List<TreeAccountDto> children { get; set; } = new();
    }

    public class AccountDto
    {
        public int? id { get; set; }
        public string? accountCode { get; set; }
        public string? userId { get; set; }
        public string accountName { get; set; } = default!;
        public int type { get; set; }
        public int? parentAccountId { get; set; }
        public bool isLeaf { get; set; }
        public bool isActive { get; set; }
        public bool isSystemAccount { get; set; }   // NEW (read-only on UI)
    }
    public class DisAndMerchAccountDto()
    {
        public string accountCode { get; set; }
        public string? userId { get; set; }
        public string accountName { get; set; }
        public int type { get; set; }
        public int? parentAccountId { get; set; }
        public bool isLeaf { get; set; }
        public bool isActive { get; set; }
        public decimal debit { get; set; }
        public decimal credit { get; set; }
    }

    public class AccountDetailsDtoReq
    {
        public int accountId { get; set; }
        public int page { get; set; }
        public int pageSize { get; set; }
        public int?entryId { get; set; }
        public DateTime? entryDate { get; set; }
    }
    public class AccountDetailsDto
    {
        public int accountId { get; set; }
        public string accountName { get; set; }
        public string accountCode { get; set; }
        public int type { get; set; }
        public bool isActive { get; set; }

        public decimal currentBalance { get; set; }

        public ApiResponse<List<AccountMovementDto>> movements { get; set; }
    }
    public class AccountMovementDto
    {
        public int entryId { get; set; }
        public DateTime entryDate { get; set; }
        public string description { get; set; }
        public decimal debit { get; set; }
        public decimal credit { get; set; }
        public decimal runningBalance { get; set; }
    }
    public class AccountTotals
    {
        public decimal Debit { get; set; }
        public decimal Credit { get; set; }
    }


    // ---- existing TreeAccountDto, AccountDto, DisAndMerchAccountDto, etc. stay as-is ----

    /// <summary>
    /// Input contract for creating a new account in the chart of accounts.
    /// Intentionally does NOT expose AccountCode — the code is generated by the
    /// system based on the parent's code, and clients have no say in it.
    /// Intentionally does NOT expose Id or Type — Type is inherited from the parent.
    /// </summary>
    public class CreateAccountDto
    {
        /// <summary>
        /// Optional link to a domain user (supplier, customer, distributor...).
        /// Null for purely accounting nodes.
        /// </summary>
        public string? userId { get; set; }

        /// <summary>
        /// Display name of the account (Arabic or English).
        /// </summary>
        [Required(ErrorMessage = "اسم الحساب حقل ضروري")]
        [MaxLength(200, ErrorMessage = "اسم الحساب لا يمكن أن يتجاوز 200 حرف")]
        public string accountName { get; set; } = default!;

        /// <summary>
        /// The parent account ID under which this new account is created.
        /// Type and code are derived from the parent.
        /// </summary>
        [Required(ErrorMessage = "لا يمكن إضافة حساب بدون حساب أب")]
        public int? parentAccountId { get; set; }

        /// <summary>
        /// True if this account is a leaf (postable) account, false for a parent node.
        /// </summary>
        public bool isLeaf { get; set; } = true;

        /// <summary>
        /// Active flag — inactive accounts cannot be used in new transactions.
        /// </summary>
        public bool isActive { get; set; } = true;
    }
}
